version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: automind-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: automindblog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/automind-backend:latest
    container_name: automind-backend
    environment:
      PORT: 4000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: automindblog
      HF_API_TOKEN: ${HF_API_TOKEN}
    depends_on:
      - postgres
    restart: always
    ports:
      - "4000:4000"

  frontend:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/automind-frontend:latest
    container_name: automind-frontend
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata: